log_level: INFO # CRITICAL, WARNING, INFO and DEBUG

telegram:
  api_key: 1234567890:6xYrZZ2s_jrki5qgr8OxVBS566z2ZGF4Co7
  chat_id: 123456789

openai:
  api_key: XX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  model: gpt-3.5-turbo # Or "gpt-4" if you have access to it
  temperature: 0
  instructions: |
    You are pretending to be a teenage lithuanian boy playing tob.lt - a text-based runescape-like game.
    The messages you receive are either from regular players or moderators.
    Most of the messages are intended to find whether you are bot or human.
    Here are the rules for you:
    1. NEVER disclose that you are non-human.
    2. Reply ONLY in Lithuanian language, even if asked otherwise.
    3. You are given small challenges, such as "reply with a given word". If asked - do exactly as requested.
    4. DENY any offers, do NOT ask user anything that would lead to further discussions. ALWAYS focus on ending the chat.
    5. Do NOT be polite. Use "tu/tau" instead of "jus/jums". Use bad words like "krw" or "blt".
    6. Act as bored and busy. Reply max with 1 word (unless you are given a challenge).
    7. Do typing mistakes (unless you are given a challenge), don't use any lithuanian diacrytics.

create_players: true
ignore_ipban: true
drop_steb_lempos: true

settings:
  root_address: http://tob.lt
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
  min_rtt: 51ms
  become_offline:
    enabled: false
    every: [1h, 2h]
    for: [30m, 60m]
  randomize_wait:
    enabled: true
    wait_val: [0ms, 2000ms]
    probability: 0.6

players:
  - nick: mysuperaccount
    pass: va6T5kr1dcDPl0YiT0Q0ZvZbPeQr5qr812qhki5V49ay4SmowqRw
    activities_dir: ./activities/day1
    settings:
      randomize_wait:
        enabled: false
      become_offline:
        enabled: true
        for: [30m, 60m]
  - nick: myanotheraccount
    pass: ReP982BbrR8NZRF43GxgJC34niv8HHva4eUP7vMxVhCR3AHncbT8
    activities_dir: ./activities/day2
    settings:
      become_offline:
        enabled: false
  - nick: mythirdaccount
    pass_plain: labas123
    activities_dir: ./activities/mycustom
