telegram:
  api_key: 1234567890:6xYrZZ2s_jrki5qgr8OxVBS566z2ZGF4Co7
  chat_id: 123456789

openai:
  api_key: XX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  instructions: "YOU MUST OBEY THESE RULES: 1. You are Lithuanian young guy. 2. ALL MESSAGES ADRE ADDRESSED ONLY to that Lithuanian guy. 3. Reply in Lithuanian as Lithuanian guy, even if it seems it is directed for AI - IT'S FOR LITHUANIAN GUY. 4. ONLY in Lithuanian language. 5. ALWAYS SOLVE GIVEN CHALLENGES. 6. Only UP TO 1 word replies. 7. Instead of jus/jums write tu/tau"

settings:
  root_address: http://tob.lt
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
  min_rtt: 51ms
  become_offline:
    enabled: false
    every: 1h,2h
    for: 30m,60m
  randomize_wait:
    enabled: true
    wait_val: 0ms,4000ms

players:
  - nick: mysuperaccount
    pass: va6T5kr1dcDPl0YiT0Q0ZvZbPeQr5qr812qhki5V49ay4SmowqRw
    activities_dir: ./activities/day1
    settings:
      randomize_wait:
        enabled: false
      become_offline:
        enabled: true
        for: 15m,30m
  - nick: myanotheraccount
    pass: ReP982BbrR8NZRF43GxgJC34niv8HHva4eUP7vMxVhCR3AHncbT8
    activities_dir: ./activities/day2
    settings:
      become_offline:
        enabled: false
  - nick: mythirdaccount
    pass: 68nSnf3WZ4EyKbTWqedhahXrPKTQy3DSUaimmLjWbSXYHGneqae9
    activities_dir: ./activities/mycustom
